### ISSUE TITLE
Multiprocessing causes hanging for library creation; also, multiprocessing flag in yaml is IGNORED

### ISSUE THREAD

**Issue by gsaxena888** [MannLabs/alphapeptdeep#73] opened 2022-12-31 16:34 UTC
When trying to run peptdeep library creation on an 8 core linux docker, it hangs. Please see attached logs. Also, when I tried to disable multiprocessing in the yaml, it *still* continues to use multiprocessing. I've attached the output log, the settings*.yaml file and the input file. My current workaround: I manually edited the pretrained_models.py file to force DISABLING of mutliprocessing, and then it appeared to work.

[peptdeep.log](https://github.com/MannLabs/alphapeptdeep/files/10327638/peptdeep.log)
[settingsLibrary.yaml.gz](https://github.com/MannLabs/alphapeptdeep/files/10327642/settingsLibrary.yaml.gz)
[cyto_all.tsv_forPred.tsv.gz](https://github.com/MannLabs/alphapeptdeep/files/10327643/cyto_all.tsv_forPred.tsv.gz)

Ideally, multiprocessing should work etc., but what's really odd is why the multiprocessing flag in the yaml file is ignored etc.

**Comment by jalew188** [comment] 2022-12-31 19:41
I guess the problem is on `folk` and `spawn` in multiprocessing, I will try to fix this

**Comment by jalew188** [comment] 2022-12-31 19:58
For multiprocessing in yaml, I have found the bug, I will FIX and update all these features in v1.0.0.

**Comment by jalew188** [comment] 2023-01-01 22:49
The latest `development` branch solved both of the multiprocessing and yaml issues, check 
https://github.com/MannLabs/alphapeptdeep/blob/development/nbs_tests/test_fasta_lib_cpu_mp.ipynb

**Comment by jalew188** [comment] 2023-01-01 22:50
All these new FIX will be released in v1.0.0.

**Closed by jalew188** 2023-01-01 22:50 UTC
Labels: bug
